### ISSUE TITLE
.net Framework Update ?

### ISSUE THREAD

**Issue by kilroyFR** [autofac/Autofac.Extras.AggregateService#15]
hey there, any chance a version of the nuget with a framework update (.net Standard or Core) ?

Thanks !

**Comment by tillig** [comment]
Currently released version 6.1.2 targets `netstandard2.0` and `netstandard2.1`.

**Comment by kilroyFR** [comment]
It's just that i am getting vulnerabilities issues (warning NU1903)
on System.Net.Http 4.3.0 and System.Text.RegularExpressions 4.3.0

**Comment by tillig** [comment]
That sounds like you need to add some direct references to your project to update those. [We don't reference either of those packages.](https://github.com/autofac/Autofac.Extras.AggregateService/blob/develop/src/Autofac.Extras.AggregateService/Autofac.Extras.AggregateService.csproj) We also [intentionally don't always reference the latest Autofac core or other dependencies](https://autofac.readthedocs.io/en/latest/faq/binding-redirect.html) to avoid forcing people to take upgrades they don't want.
