### ISSUE TITLE
Add support for netstandard 1.3 when Castle.Core 4.0.0 is released

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Extras.AggregateService#3]
It appears [Castle.Core is working on supporting netstandard 1.3](https://github.com/castleproject/Core/blob/netcore/buildscripts/Castle.Core.nuspec) which would open up the platform support for the aggregate service library. When that's available, we should update to Castle.Core 4.0.0 and support netstandard.

**Comment by zahik** [comment]
Any Progress?
Thanks

**Comment by tillig** [comment]
We can't make progress until Castle.Core is released for netstandard 1.3. Feel free to [watch their published package on NuGet](https://www.nuget.org/packages/Castle.Core) and let us know when the 4.0 stable release is out. Once that's out, we can _begin_ work.

**Comment by tillig** [comment]
Looks like [4.0.0 is released](https://www.nuget.org/packages/Castle.Core/4.0.0) so we can start making some headway on this.

**Comment by tillig** [comment]
Released [4.1.0](https://www.nuget.org/packages/Autofac.Extras.AggregateService/4.1.0) with support for netstandard 1.3 and .NET 4.5.

**Comment by tzahik1** [comment]
Great!
Thanks @tillig

**Comment by alexmg** [comment]
Nice one @tillig 👍
